python3 data-standardization.py
Trying to read tracker file from: /home/kali/Desktop/script/process-pentest/files/input/other/Archer.xlsx
Trying to read tracker file from: /home/kali/Desktop/script/process-pentest/files/input/other/Database.xlsx
Trying to read tracker file from: /home/kali/Desktop/script/process-pentest/files/input/other/Ports.xlsx
Trying to read tracker file from: /home/kali/Desktop/script/process-pentest/files/input/other/Scope.xlsx
Trying to read tracker file from: /home/kali/Desktop/script/process-pentest/files/input/other/Vulnerability.xlsx
Output File Path: /home/kali/Desktop/script/process-pentest/files/output/vendor-tracker-updated.xlsx
Attempting to read from: /home/kali/Desktop/script/process-pentest/files/output/vendor-tracker.xlsx
Attempt Successful: /home/kali/Desktop/script/process-pentest/files/output/vendor-tracker.xlsx
Columns in results_df: Index(['Region', 'Country', 'IP', 'Port', 'Protocol', 'Vulnerability',
       'Severity', 'Category', 'Status', 'Description', 'Impact',
       'Recommendation', 'CVE', 'CWE', 'CVSS', 'Fix-Owner',
       'Stakeholder-Comments', 'Vendor-Reported-Date',
       'Internal-Reported-Date', 'Due-Date', 'Over-SLA', 'Assigned-Pentester',
       'Tracking-Doc', 'Status-Update', 'MIST-Owner', 'MIST-Team-Notes',
       'Char-Count', 'Unique-ID', 'mapped-vulnerability', 'reason',
       'Updated Entry', 'UID', 'status', 'notes'],
      dtype='object')
Index(['common name', 'Vulnerability'], dtype='object')
Script completed successfully.
Traceback (most recent call last):
  File "/home/kali/Desktop/script/final-cuts/data-standardization.py", line 294, in <module>
    gold_tracker_results = pd.read_excel(gold_tracker_path, sheet_name="results")
  File "/usr/lib/python3/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 1191, in __init__
    ext = inspect_excel_format(
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 1090, in inspect_excel_format
    zf = zipfile.ZipFile(stream)  # type: ignore[arg-type]
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
